---
- hosts: vag
  remote_user: vagrant
  tasks:

    - name: make a install file save folder
      sudo: yes
      file: path=/opt/AnsibleTemp/InstallSave/YumRepo state=directory

    - name: back up current repo file
      sudo: yes
      shell: "if [ -f './CentOS-Base.repo' ]; then echo 'do nothing'; else echo 'moving'&& mv /etc/yum.repos.d/* .; fi"
      args:
        chdir: "/opt/AnsibleTemp/InstallSave/YumRepo"

    - name: download ali repo file
      sudo: yes
      shell: wget -O /etc/yum.repos.d/CentOS-Base.repo http://mirrors.aliyun.com/repo/Centos-6.repo
      args:
        chdir: "/etc/yum.repos.d"